.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bpq_qt test_bpq_qt
clean: FORCE
	$(MAKE) -C .. bpq_qt_clean test_bpq_qt_clean
check: FORCE
	$(MAKE) -C .. test_bpq_qt_check
bpq-qt bpq-qt.exe: FORCE
	 $(MAKE) -C .. bpq_qt
